- name: Deploy Server Profiles
  connection: local
  gather_facts: false
  hosts: localhost
  vars:
    # Create an anchor for api_info that can be used throughout the file
    # api_info: &api_info
    #   # if api_key vars are omitted, INTERSIGHT_API_KEY_ID, INTERSIGHT_API_PRIVATE_KEY,
    #   # and INTERSIGHT_API_URI environment variables used for API key data
    #   api_private_key: "{{ api_private_key | default(omit) }}"
    #   api_key_id: "{{ api_key_id | default(omit) }}"
    #   api_uri: "{{ api_uri | default(omit) }}"
    #   validate_certs: "{{ validate_certs | default(omit) }}"
    #   state: "{{ state | default(omit) }}"
    # # Server Profile name default
    # profile_name: "SP-{{ inventory_hostname }}"
    # profile_action: Deploy
  tasks:
    # - name: Find Server Profiles to deploy
    #   cisco.intersight.intersight_rest_api:
    #     # <<: *api_info
    #     resource_path: /server/Profiles
    #     query_params:
    #       $filter: "Tags/any(t:t/Key eq 'ansible' and t/Value eq 'deploy')"
    #     return_list: true
    #   delegate_to: localhost
    #   register: sp_result
    # - name: List SP moids
    #   ansible.builtin.debug:
    #     msg: "{{ sp_result | community.general.json_query('api_response[*].Moid') }}"
    #   # loop: "{{ sp_result | community.general.json_query('Results[*].Moid') }}"
    # Deploy (or perform other action)
    # action can be given on the command line if needed, e.g., ansible-playbook ... -e profile_action=Unassign
    # to delete a profile (profile must 1st be unassigned): ansible-playbook ... -e state=absent -e profile_action=No-op
    - name: Deploy Server Profile
      cisco.intersight.intersight_rest_api:
        # <<: *api_info
        resource_path: /server/Profiles/6848c8c777696e330149d3a7
        # query_params:
        #   $filter: "Tags/any(t:t/Key eq 'ansible' and t/Value eq 'deploy')"
        api_body:
          {
            "ScheduledActions":
              [{ "Action": "Deploy", "ProceedOnReboot": false }],
          }
      delegate_to: localhost
