- name: Deploy Server Profiles
  connection: local
  gather_facts: false
  hosts: localhost
  tasks:
    - name: Deploy Server Profile
      cisco.intersight.intersight_rest_api:
        # <<: *api_info
        resource_path: /server/Profiles
        query_params:
          $filter: "Tags/any(t:t/Key eq 'ansible' and t/Value eq 'deploy')"
        api_body:
          {
            "ScheduledActions":
              [{ "Action": "Deploy", "ProceedOnReboot": false }],
          }
      delegate_to: localhost
